mortbopet/Ripes

- src/defines.h
- src/lexerutilities.h
This regex is a bit of a kludge and has several non-capturing groups as well as some lookaheads. It also wouldn't accept the floating point registers (but my understanding is that support for RV32F/RV32D is not available yet).
If a type has the same name as a register, then this will break. I am unsure of how that can be avoided without more complex changes than to just the regex. Hopefully in Compiler Explorer examples, that wouldn't be an issue.
Resolves #10
> Adjust splitter regex to allow parentheses

- src/parser.cpp
thethirdone/rars#28 brought unicode to my attention and I tested Ripes to see if it could handle unicode text. 
I found Ripes can input from `.asciz` just fine as UTF-8, but couldn't print those strings.
A quick test program:
```
.data
label:
.asciz "█"
.text
li a0, 4
la a1, label
ecall
```
Current output:
With this PR:
> Make print_string support UTF-8

- src/pipeline.cpp
The signal `loadUseHazard` is wrongly calculated in `hazardControlGen` function in pipeline. 
The conversion of `r_MemRead_IDEX` to `bool` will only look at the last bit of `s_MemRead`, which may be assigned to enum `MemRead` that can be greater than 1.
There is a simple program that can trigger this bug:
```asm
li a0, 1000
li a1, 2000
sb a0, 0(a1)
lbu a0, 0(a1)
addi a2, a0, 0
```
The correct value of `a2` should be `1000`, but Ripes actually gives `2000`. Using `LBU` and `LH` willl cause this problem, while `LB`, `LW` and `LHU` won't, which corresponds to their actual values in the enum `MemRead`.
> Wrong type conversion in the generation of hazard control signals

- examples/assembly/Complex multiplication
- examples/assembly/Console printing
- examples/assembly/Factorial function
My editor automatically removed some white-space. If you want I can strip those changes out.
If you'd rather keep the non-pseudo instructions just let me know. Just wanted to add a convenient trick I learned today :)
Thanks for the great app!
> Replace `jalr x0 x1 0` with psuedo-op `jr x1` in examples

- src/assembler/instruction.h
- src/assembler/pseudoinstruction.h
- src/assembler/rv32i_assembler.cpp
Hi @mortbopet ,
Referring to your opinion, we have a little progress in implementing this issues.
We have added a parameter at the instruction definition for determining the type (Reg or Imm) in  rv32i_assembler.cpp.
Otherwise, we also add some code to represent our desired result in instruction.h.
> [Assembler] Hint for assembler editor

- src/programviewer.cpp
This PR fix address map to put breakpoints correctly in programviewer when RVC instructions are present.
> fix address map to put breakpoints

- src/assembler/assembler.h
- src/isa/isainfo.h
- src/isa/rv32isainfo.h
- src/isa/rv64isainfo.h
- test/riscv-tests-c-64/rvc.s
- test/riscv-tests-c/rvc.s
This PR implement the instruction alignment constraint relax tho 16bits when RVC is enabled and remove the `c.nop` pad instructions from tests. It will close https://github.com/mortbopet/Ripes/issues/124.
> Relax instruction alignment constraint when RVC is enabled

- src/ccmanager.cpp
- src/editor/codeeditor.cpp
- src/editor/codeeditor.h
- src/edittab.cpp
- src/edittab.h
- src/formattermanager.h
- src/mainwindow.cpp
- src/mainwindow.h
- src/processmanager.h
- src/ripessettings.cpp
- src/ripessettings.h
- src/settingsdialog.cpp
- src/settingsdialog.h
- src/utilities/systemutils.cpp
- src/utilities/systemutils.h
This commit adds support for running clang-format on C source code. `clang-format` must be available in PATH.
> Add clang-format support #181

- src/assembler/rv_i_ext.h
The bgtu and bleu instructions were using the same token twice when generating the corresponding instruction. This was fixed by correctly swapping the first two tokens of these pseudo-instructions as expected.
> Fix bgtu and bleu pseudo-instructions to swap tokens correctly

- src/processors/RISC-V/rv_uncompress.h
- test/riscv-tests-c/rvc.s
This PR fixes a bug in decoding the compressed instructions c.bnez and c.beqz.
> Fix offset of compressed instructions c.bnez and c.beqz

- main.cpp
- src/CMakeLists.txt
- src/cmd/CMakeLists.txt
- src/cmd/cmdoptions.cpp
- src/cmd/cmdoptions.h
- src/cmd/cmdrunner.cpp
- src/cmd/cmdrunner.h
- src/cmd/programutilities.cpp
- src/cmd/programutilities.h
- src/edittab.cpp
- src/edittab.h
- src/processorregistry.h
- src/syscall/control.h
This commit introduces initial support for command-line execution of Ripes.
Command-line mode is enabled when providing the "--mode sh" argument. Based on an input source file, Ripes will assemble the program, execute it, and report back any requested telemetry.
> Initial commit for Ripes command line mode

- src/processorregistry.cpp
Prior to this commit, switching to the extended layout for the 5-stage processor would crash Ripes with a 'std::out_of_range' exception caused by `map::at`.
This renders Ripes unusable until `processor_layout_id=1` was removed or set to `0` in the configuration as Ripes would also crash on startup.
> Fix crash when using extended layout for 5-stage processor.

- docker/ripes.dockerfile
Without this variable the following error occurs when running an application in a container:
`Ripes: error while loading shared libraries: libQt6Charts.so.6: cannot open shared object file: No such file or directory`
> Add missing LD_LIBRARY_PATH variable with Qt libs in ripes.dockerfile

- src/assembler/rv64i_assembler.cpp
- src/assembler/rv_c_ext.h
- src/assembler/rv_i_ext.h
- src/assembler/rv_m_ext.h
- src/assembler/rvassembler_common.h
- src/ctkrangeslider.h
- src/isa/rvisainfo_common.h
> Refactor instruction definitions from macros to classes

- .github/workflows/clang-format.yml
This change filters out deleted files from being formatted in pull request checks.
> Update clang-format PR check to not throw errors when files are removed

- src/cachesim/chartlinemarker.cpp
This crash would occur when hovering over the cache statistics chart when there are no points on it (fixes #322).
Thanks to @margheritarufi for reporting!
> Fix crash when hovering over the cache statistics chart while empty

- src/processorhandler.h
- src/statusmanager.h
- src/syscall/file.h
- src/syscall/systemio.h
- test/riscv-tests-64/ecall_file.S
- test/riscv-tests/ecall_file.s
- test/tst_riscv.cpp
When working with file operations, the ecall instruction would not recognize the `O_RDONLY` flag. It would also accidentally use the `QIODevice::Append` flag in read-only mode, which would then silently fail and return the wrong characters. This fixes the flags so that read-only files return the correct characters (fixes #316).
Thanks to @lukasrad02 for reporting!
> Fix ecall support for read-only file operations

- src/syscall/systemio.h
In the open syscall, a new file would be created if the opened file didn't exist and the `O_CREAT` flag was NOT set.
This has been fixed to create a new file only if the `O_CREAT` flag IS set. This matches the original Unix flag.
> Fix O_CREAT flag in open syscall

- src/isa/isainfo.h
- src/isa/pseudoinstruction.h
Virtual destructors that were previously missing have been added to the following abstract classes:
* `RegFileInfoInterface`
* `PseudoInstructionBase`
This fixes #331.
> Add missing virtual destructors to abstract classes

- src/cli/clioptions.cpp
- src/cli/clirunner.cpp
- src/cli/programutilities.cpp
- src/cli/programutilities.h
- src/edittab.cpp
- src/edittab.h
- src/syscall/file.h
In the Command Line Interface mode, although the possible execution file types are `c, asm, bin` (as shown by the command-line option `--t`), it is not possible to simulate `C` programs.
```
int Ripes::CLIRunner::processInput(): Assertion `false && "Command-line support for this source type is not yet implemented"' failed.
Aborted (core dumped)
```
This has been fixed with the possibility to execute *RISC-V* `ELF` files too. 
In the `clirunner.cpp` file I've added the logic to load three new source types: `C`, `InternalELF` and `ExternalELF`. 
For an ELF file first a check is done to be sure that the specified file is valid for the selected processor and then the file is loaded with the method `loadElfFile`. I moved this method to the `programutilities.cpp` file, following what was done …
> Add CLI Support for Executing ELF and C Files

- src/console.cpp
In the current  WebAssembly (WASM) version of Ripes there's an issue preventing input reading from the console. This because pressing `Enter` does not return control to the processor, as stated in issue #304.
The problems stems from the behaviour of the `Console::keyPressEvent(QKeyEvent *e)` method, which requires a `QKeyEvent` parameter, that appears to behave differently in the binary executable compared to the WASM version. 
In the binary executable, when pressing Enter or Return, the `QKeyEvent` associated with the keys `Qt::Key_Return` or `Qt::Key_Enter` has a non empty text field (`e->text()`). However, in the WASM version that field is empty and therefore the check `if (!e->text().isEmpty())` always returns false when pressing Enter, resulting in the already reported error.
The …
> Fix Issue: WASM, Reading console input does not work

- src/syscall/control.h
- test/riscv-tests-64/brk_syscall.S
- test/riscv-tests/brk_syscall.s
Implemented additional checking in the `execute()` method of the brk syscall, defined in the `BrkSyscall` class, to ensure that memory allocation does not overflow stack space. The System Call has as its argument the new "program break", which is now compared with the current "stack pointer" before being set to avoid overlaps.
This commit resolves a @todo present in the code.
> Add stack-heap collision check to BrkSyscall execution

- .github/workflows/clang-format.yml
- .github/workflows/linux-release.yml
- .github/workflows/mac-release.yml
- .github/workflows/wasm-release.yml
- .github/workflows/windows-release.yml
Fix [deprecated version](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/) of `actions/upload-artifact` in workflows. 
Fixes: #380.
> Fix Deprecation Error

- main.cpp
Ditto. Fixes  #375. 
P.S.: Please notice that the failures in the docker image and code format tests are due to the tests having rot away and are unrelated with the PR itself.
> Fix: change '--mode sh' to '--mode cli' in help text

- src/assembler/expreval.cpp
Added checks in the expression evaluation (`evaluate`) method of `expreval.cpp` for division (`/`) and modulo (`%`) operations to prevent zero as a divisor.
Checks are performed by calculating and evaluating the _right-hand side value_ (`rhs_value`) of the binary operation. 
Used `std::runtime_error` to handle the case of division by zero so that the error is shown to the user directly in the written code in the text editor.
This fixes issue #347.
> Fix Issue: Division by zero crash in assembler constant expressions

- src/assembler/assemblerbase.cpp
Ripes assembler gives an error for any identifier that starts with a dot. However, such syntax seems valid and is in fact routinely used by GCC. 
This patch changes this, making copying and pasting from Compiler Explorer more straightforward.
> Accept labels that start with a dot.
